#!/data/data/com.termux/files/usr/bin/sh

exec 2>&1

# Make network availabe for all your container and it will also let them communicate with each-other
# It will get your current getway ip
getway=$(sudo ip route get 8.8.8.8 | grep -oP '(?<=via )[^ ]*')

#it will add your getway ip to your iptable rules in android

sudo ip route add default via $getway dev wlan0
sudo ip rule add from all lookup main pref 30000
sudo ip rule add pref 1 from all lookup main
sudo ip rule add pref 2 from all lookup default

# It will make storage writable to add some file and folders docker require
sudo mount -o remount,rw /

# It will make cgroup mountable as existing process in dockerd can not mount properly
sudo mount -t tmpfs -o mode=755 tmpfs /sys/fs/cgroup
sudo mkdir -p /sys/fs/cgroup/devices
sudo mount -t cgroup -o devices cgroup /sys/fs/cgroup/devices

exec sudo /data/data/com.termux/files/usr/bin/dockerd